version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"